# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpr9oY3cJFz7InRGRYavJNkBEVE5kwPZ
"""

pip install pandas matplotlib

!pip install pandas matplotlib

import pandas as pd
import matplotlib.pyplot as plt

# 1. So'rovnoma ma'lumotlarini yaratish
data = {
    'Ism': ['Dilyorbek', 'Sarvarbek', 'Bekmurod', 'Gulnoza', 'Madina', 'Sardor'],
    'lavozim': ['dasturchi', 'Dizayner', 'Boshqaruvchi', 'dasturchi', 'tahlilchi', 'boshqaruvchi'],
    'staji': [2, 5, 8, 1, 3, 6],
    'ish_haqqi': [2000, 3000, 5000, 1500, 2500, 4000]
}
df = pd.DataFrame(data)

# Ma'lumotlarni ko'rsatish
print("Asosiy ma'lumotlar:")
print(df)

# 2. Tajribasi 3 yildan ko'p bo'lgan nomzodlarni filtrlash
filtered_df = df[df['staji'] > 3]
print("\nFiltrlangan ma'lumotlar (3 yildan ko'p tajribaga ega):")
print(filtered_df)

# 3. Vizualizatsiya: Tajriba bo'yicha taqsimot
plt.figure(figsize=(10, 6))
plt.bar(df['Ism'], df['staji'], color='skyblue', label='staji')
plt.title('Nomzodlarning Tajribasi')
plt.xlabel('Nomzodlar')
plt.ylabel('Tajriba (Yillar)')
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.savefig('experience_distribution.png')  # Diagrammani saqlash
plt.show()

# 4. Vizualizatsiya: Lavozim bo'yicha taqsimot
position_counts = df['lavozim'].value_counts()
plt.figure(figsize=(8, 6))
position_counts.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['gold', 'lightgreen', 'skyblue'])
plt.title('Lavozimlarga Qiziqish Taqsimoti')
plt.ylabel('')  # Y o'qi ko'rsatilmaydi
plt.savefig('position_distribution.png')  # Diagrammani saqlash
plt.show()

# 5. Filtrlangan ma'lumotlarni eksport qilish
filtered_df.to_csv('filtered_candidates.csv', index=False)
print("\nFiltrlangan ma'lumotlar 'filtered_candidates.csv' fayliga saqlandi.")

# Xabarni tugatish
print("\nTahlil tugallandi. Natijalar diagramma va CSV fayllarda saqlandi.")